### ISSUE TITLE
Орфографічні помилки

### ISSUE THREAD

**Issue by Volodymyr-Ukraine** [swiftbookua/swiftbookua#4]
https://github.com/swiftbookua/swiftbookua/blob/feat/separate-jekyll-deployment/0_welcome_to_swift/swift_tour/3_functions_and_closures.md

Виправте будь ласка:
Ексеримент -> ЕксПеримент

Те саме для глав 4-8

**Comment by killobatt** [comment]
Дякую за повідомлення, виправлено.
